-- ============================================================================
--  BALUNI HOSTEL MANAGEMENT v3 — database upgrade
--  Safe to run on your EXISTING Supabase project (it only adds; never deletes data).
--  Run ONCE in Supabase Dashboard → SQL Editor → New query → paste all → Run.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Role helper: principal check used by all security policies
-- ---------------------------------------------------------------------------
create or replace function is_principal()
returns boolean language sql stable as
$$ select coalesce(auth.jwt()->>'email','') = 'principal@hostel.app' $$;

-- ---------------------------------------------------------------------------
-- 1. Base tables (created only if missing — your existing data is untouched)
-- ---------------------------------------------------------------------------
create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  wing text not null,
  name text not null,
  class text, roll_no text,
  guardian_name text, guardian_phone text,
  address text, blood_group text, medical_condition text,
  room text, bed_no text, almirah_no text,
  admission_date date
);
-- v3 extra student columns
alter table students add column if not exists father_name   text;
alter table students add column if not exists father_phone  text;
alter table students add column if not exists mother_name   text;
alter table students add column if not exists mother_phone  text;
alter table students add column if not exists dob           date;
alter table students add column if not exists admission_no  text;

create table if not exists attendance (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  date date not null,
  session text not null,              -- Morning | Evening | Night
  wing text,
  student_id uuid references students(id) on delete cascade,
  student_name text, room text,
  status text not null,               -- Present | Absent | Leave | Outpass | Sick
  marked_by text,
  unique (date, session, student_id)
);

create table if not exists fines (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  date date default current_date,
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  reason text, amount numeric,
  paid boolean default false,
  collected_by text
);

create table if not exists medical (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  date date default current_date,
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  condition text, treatment text,
  severity text
);

create table if not exists leaves (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  from_date date, to_date date,
  reason text, destination text,
  approved_by text
);
alter table leaves add column if not exists status text default 'Approved';  -- Pending | Approved | Rejected
alter table leaves add column if not exists parent_consent boolean default false;

-- ---------------------------------------------------------------------------
-- 2. New v3 tables
-- ---------------------------------------------------------------------------
create table if not exists outpass (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  pass_no bigint generated by default as identity,
  date date default current_date,
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  time_out text, expected_return text,
  destination text,
  guardian_name text, guardian_phone text,
  returned_at timestamptz,            -- null = still out
  issued_by text
);

create table if not exists discipline (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  date date default current_date,
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  category text,                      -- Uniform | Cleanliness | Late | Mobile misuse | Homework | Fighting | Other
  details text, action text,
  points int default 1,               -- penalty points
  reported_by text,
  resolved boolean default false
);

create table if not exists complaints (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  date date default current_date,
  ticket_no bigint generated by default as identity,
  source text,                        -- Student | Parent
  student_id uuid references students(id) on delete set null,
  student_name text, wing text,
  category text,                      -- Food | Room | Water | Electricity | Health | Academic | Discipline | Other
  details text,
  status text default 'Pending',      -- Pending | In Progress | Resolved
  handled_by text
);

create table if not exists parent_calls (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  student_id uuid references students(id) on delete cascade,
  student_name text, wing text,
  call_date date default current_date,
  start_time text, end_time text,
  minutes int,
  parent_name text, staff_name text,
  notes text
);

-- ---------------------------------------------------------------------------
-- 3. Row Level Security — real enforcement, not just hidden buttons
--    Principal: full access everywhere.
--    Warden: can READ and ADD entry records; can update attendance (re-save)
--            and outpass returns; CANNOT touch the students table at all,
--            and cannot edit or delete history.
-- ---------------------------------------------------------------------------
alter table students     enable row level security;
alter table attendance   enable row level security;
alter table fines        enable row level security;
alter table medical      enable row level security;
alter table leaves       enable row level security;
alter table outpass      enable row level security;
alter table discipline   enable row level security;
alter table complaints   enable row level security;
alter table parent_calls enable row level security;

-- Remove EVERY existing policy on our tables (whatever earlier setup scripts named them),
-- then recreate the correct role-aware set below. This guarantees no old permissive
-- policy survives to give wardens more access than intended.
do $$
declare r record;
begin
  for r in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('students','attendance','fines','medical','leaves','defaulters',
                        'outpass','discipline','complaints','parent_calls')
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- students: PRINCIPAL ONLY (wardens use the roster function below)
drop policy if exists "principal only" on students;
create policy "principal only" on students
  for all to authenticated using (is_principal()) with check (is_principal());

-- entry tables: everyone signed-in can read + add; edits/deletes controlled
do $$
declare t text;
begin
  foreach t in array array['attendance','fines','medical','leaves','outpass','discipline','complaints','parent_calls'] loop
    execute format('drop policy if exists "read"   on %I', t);
    execute format('drop policy if exists "add"    on %I', t);
    execute format('drop policy if exists "edit"   on %I', t);
    execute format('drop policy if exists "remove" on %I', t);
    execute format('create policy "read" on %I for select to authenticated using (true)', t);
    execute format('create policy "add"  on %I for insert to authenticated with check (true)', t);
    execute format('create policy "remove" on %I for delete to authenticated using (is_principal())', t);
  end loop;
end $$;

-- updates: principal everywhere; warden also on attendance (re-save marks)
-- and outpass (recording the student's return is gate duty)
create policy "edit" on attendance   for update to authenticated using (true) with check (true);
create policy "edit" on outpass      for update to authenticated using (true) with check (true);
create policy "edit" on fines        for update to authenticated using (is_principal()) with check (is_principal());
create policy "edit" on medical      for update to authenticated using (is_principal()) with check (is_principal());
create policy "edit" on leaves       for update to authenticated using (is_principal()) with check (is_principal());
create policy "edit" on discipline   for update to authenticated using (is_principal()) with check (is_principal());
create policy "edit" on complaints   for update to authenticated using (is_principal()) with check (is_principal());
create policy "edit" on parent_calls for update to authenticated using (is_principal()) with check (is_principal());

-- ---------------------------------------------------------------------------
-- 4. Warden roster — names/wing/class/room ONLY (no address, phones, medical)
--    This is how wardens see the student list without access to private details.
-- ---------------------------------------------------------------------------
create or replace function students_roster()
returns table (id uuid, name text, wing text, class text, room text, bed_no text)
language sql stable security definer set search_path = public as
$$ select id, name, wing, class, room, bed_no from students order by name $$;

revoke all on function students_roster() from public, anon;
grant execute on function students_roster() to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_students_wing  on students (wing);
create index if not exists idx_att_date       on attendance (date, session, wing);
create index if not exists idx_fines_paid     on fines (paid);
create index if not exists idx_leaves_dates   on leaves (from_date, to_date);
create index if not exists idx_outpass_open   on outpass (returned_at);
create index if not exists idx_disc_resolved  on discipline (resolved);
create index if not exists idx_compl_status   on complaints (status);
create index if not exists idx_calls_student  on parent_calls (student_id, call_date);
